### ISSUE TITLE
Not working for v8.1.0

### ISSUE THREAD

**Issue by monkii-dev** [KOBENDigital/Iconic#16] opened 2019-07-12 03:05 UTC
After upgrading to 8.1.0, when calling the control, it return string as json

({ 
  "icon": "fa-search", 
  "packageId": "8492d996-3934-4cc6-b56a-6ceaac9cba4b" 
}) 
instead of the desired IHtmlString "i class="fa fa-search"></i>"

**Comment by miackers** [comment] 2019-07-15 14:06
I am also seeing this. It has to do with 8.1 moving from PublishedPropertyType to IPublishedPropertyType (and PublishedElement to IPublishedElement etc). I managed to get around it by reproducing the IconicValueConverter in my project (using the source in this repository). You also need to run rebuild your models afterwards. 

(It was just a quick fix/try to see if it will work. If you need an urgent fix, I can send you what I have. If not urgent, i will try do a pull request etc later.)

**Comment by skartknet** [comment] 2019-07-16 03:01
This has been fixed in new 2.2 version. Please give it a try.

**Closed by skartknet** 2019-07-16 03:01 UTC

**Comment by miackers** [comment] 2019-07-16 08:37
Amazing! (didn't expect such quick turn around- thanks).

Just did an update via nuget, and it seems to be working. One thing I noticed is that .gitattributes and package.xml was added to my solution after installing (root folder)

**Comment by skartknet** [comment] 2019-07-16 22:31
Hmmm, weird, I'll take a look, thanks for letting me know.
